#!/bin/bash
. "${dirname "$0"}/_/husky.sh";

echo ' Styling, testing and building your project before commiting';

# Check Prettier
npm run check-format ||
{
    echo 'Prettier Check Failed. Run : npm run format, add changes and try commit again';
    false;
}

# Checl ESLint
npm run check-lint ||
{
    echo "ESLint Check Failed. Make the required changes listed above, add changes abd try commit again";
    false;
}

#Check TSconfig
npm run check-types ||
{
    echo "Failed type check. Make the changes require above, add changes abd try commit again";
    false;
}

npm run build ||
{
    echo "Your build failed, viiew error above";
    false;
}

echo "Success Commit";